import NewsItem from "@components/News/Item/NewsItemOld";
import { useEffect } from "react";
import { Link } from "react-router-dom";
// import { useAppDispatch, useAppSelector } from "../../hooks/hook";
// import { getNewsActive } from "../../reducers/news";

export type News = {
    id?: number
    titleVi: string
    titleEn: string
    descriptionVi: string
    descriptionEn: string
    contentVi: string
    contentEn: string
    avatarUrl: string
    avatarPath: string
    createdBy?: string,
    createdDate?: string
}

export interface NewsState {
    newsList: News[],
    newsActiveList: News[];
    total: number
    isLoading: boolean
    currentPage: number
}

export const newsData: NewsState = {
    newsList: [
        {
            id: 11,
            titleVi: "Kỹ Nghệ Xanh Việt Nam tham gia hội chợ Khoa học – Công nghệ Nam Trung Bộ – Tây Nguyên",
            titleEn: "Vietnam Green Industry participates in Science - Technology Fair South Central - Central Highlands",
            descriptionVi: "Triển lãm và Hội nghị Khoa học & Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 diễn ra từ ngày 28/6 đến hết ngày 01/07/2018 tại Nha Trang, Khánh Hòa.",
            descriptionEn: "Science & Technology Exhibition and Conference for Agricultural Development in the South Central Coast - Central Highlands 2018 took place from June 28 to July 1, 2018 in Nha Trang, Khanh Hoa.",
            contentVi: "{\"time\":1664937785587,\"blocks\":[{\"id\":\"7S--1xGAEf\",\"type\":\"paragraph\",\"data\":{\"text\":\"Bộ Khoa học Công nghệ phối hợp với các bộ, ngành địa phương tổ chức chương trình Triển lãm và Hội nghị: Khoa học &amp; Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 nhằm mục tiêu hỗ trợ phát triển nông nghiệp cho khu vực Duyên hải Nam Trung Bộ – Tây Nguyên trong việc ứng dụng khoa học công nghệ phục vụ sản xuất, xây dựng thương hiệu, đủ sức cạnh tranh trong thời kỳ hội nhập.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"13Yf8hcWBI\",\"type\":\"paragraph\",\"data\":{\"text\":\"Chương trình&nbsp;quy tụ gần 400 gian hàng của các đơn vị doanh nghiệp, hợp tác xã thuộc các tỉnh thành phố trong cả nước cùng các doanh nghiệp nước ngoài đang phát triển đầu tư tại Việt Nam. Nội dung chủ yếu của chương trình xoay quanh việc giao lưu, chia sẻ và trao đổi kinh nghiệm, quan hệ hợp tác giữa các nhà khoa học, các nhà đầu tư cùng doanh nghiệp về những thành tựu ứng dụng KHCN thành công trong lĩnh vực nông nghiệp; liên kết các viện nghiên cứu, các trường đại học với các doanh nghiệp, hợp tác xã, hộ nông dân nhằm giúp đổi mới, chuyển giao công nghệ, ứng dụng tiến bộ KHCN vào sản xuất kinh doanh nông nghiệp, đồng thời kết nối trực tiếp với các nhà cung ứng, chuyển giao uy tín và tư vấn để các đơn vị tiếp cận các chính sách ưu đãi phù hợp.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"qZEg1udWRB\",\"type\":\"paragraph\",\"data\":{\"text\":\"Kỹ Nghệ Xanh Việt Nam tham gia hội chợ với gian hàng trưng bày sản phẩm máy sấy thực phẩm đa năng.Máy sấy đa năng SUNSAY là dòng máy sấy sử dụng công nghệ mới nhất hiện nay, có thể tùy chỉnh chế độ sấy khô – sấy dẻo các sản phẩm trái cây, sấy khô nông sản, thực phẩm, thủy hải sản, dược liệu…\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"AO_-JJ9cp2\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Nguồn Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            contentEn: "{\"time\":1664937785588,\"blocks\":[{\"id\":\"gifxtfLyxG\",\"type\":\"paragraph\",\"data\":{\"text\":\"The Ministry of Science and Technology cooperates with ministries and local agencies to organize the Exhibition and Conference: Science &amp; Technology for Agricultural Development in the South Central Coast - Central Highlands 2018 with the aim of supporting the development agriculture for the South Central Coast region - Central Highlands in the application of science and technology to serve production, build brands, and be competitive enough in the integration period.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"pXtODd1Tvd\",\"type\":\"paragraph\",\"data\":{\"text\":\"The program gathers nearly 400 booths of business units, cooperatives in provinces and cities across the country and foreign businesses developing investment in Vietnam. The main content of the program revolves around the exchange, sharing and exchange of experiences and cooperation between scientists, investors and enterprises on successful achievements of science and technology application in the field of science and technology. Agriculture; linking research institutes, universities with enterprises, cooperatives, and farmer households to help innovate, transfer technology, apply scientific and technological advances to agricultural production and business, and at the same time connect directly with suppliers, transferring prestige and consulting for units to access appropriate preferential policies.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"7oQMS811hZ\",\"type\":\"paragraph\",\"data\":{\"text\":\"Green Technology Vietnam participated in the fair with a booth displaying multi-function food dryer products.\\nSUNSAY multi-function dryer is a line of dryers that uses the latest technology today, can customize the drying mode - flexible drying of fruit products, drying agricultural products, food, seafood, medicinal herbs...&nbsp;\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"P2IBKAm0Om\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Copy Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            avatarUrl: "https://www.anfico.vn/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            avatarPath: "/anfico/storage/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            createdBy: "anfico",
            createdDate: "2022-10-05T02:37:54Z"
        },
        {
            id: 11,
            titleVi: "Kỹ Nghệ Xanh Việt Nam tham gia hội chợ Khoa học – Công nghệ Nam Trung Bộ – Tây Nguyên",
            titleEn: "Vietnam Green Industry participates in Science - Technology Fair South Central - Central Highlands",
            descriptionVi: "Triển lãm và Hội nghị Khoa học & Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 diễn ra từ ngày 28/6 đến hết ngày 01/07/2018 tại Nha Trang, Khánh Hòa.",
            descriptionEn: "Science & Technology Exhibition and Conference for Agricultural Development in the South Central Coast - Central Highlands 2018 took place from June 28 to July 1, 2018 in Nha Trang, Khanh Hoa.",
            contentVi: "{\"time\":1664937785587,\"blocks\":[{\"id\":\"7S--1xGAEf\",\"type\":\"paragraph\",\"data\":{\"text\":\"Bộ Khoa học Công nghệ phối hợp với các bộ, ngành địa phương tổ chức chương trình Triển lãm và Hội nghị: Khoa học &amp; Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 nhằm mục tiêu hỗ trợ phát triển nông nghiệp cho khu vực Duyên hải Nam Trung Bộ – Tây Nguyên trong việc ứng dụng khoa học công nghệ phục vụ sản xuất, xây dựng thương hiệu, đủ sức cạnh tranh trong thời kỳ hội nhập.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"13Yf8hcWBI\",\"type\":\"paragraph\",\"data\":{\"text\":\"Chương trình&nbsp;quy tụ gần 400 gian hàng của các đơn vị doanh nghiệp, hợp tác xã thuộc các tỉnh thành phố trong cả nước cùng các doanh nghiệp nước ngoài đang phát triển đầu tư tại Việt Nam. Nội dung chủ yếu của chương trình xoay quanh việc giao lưu, chia sẻ và trao đổi kinh nghiệm, quan hệ hợp tác giữa các nhà khoa học, các nhà đầu tư cùng doanh nghiệp về những thành tựu ứng dụng KHCN thành công trong lĩnh vực nông nghiệp; liên kết các viện nghiên cứu, các trường đại học với các doanh nghiệp, hợp tác xã, hộ nông dân nhằm giúp đổi mới, chuyển giao công nghệ, ứng dụng tiến bộ KHCN vào sản xuất kinh doanh nông nghiệp, đồng thời kết nối trực tiếp với các nhà cung ứng, chuyển giao uy tín và tư vấn để các đơn vị tiếp cận các chính sách ưu đãi phù hợp.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"qZEg1udWRB\",\"type\":\"paragraph\",\"data\":{\"text\":\"Kỹ Nghệ Xanh Việt Nam tham gia hội chợ với gian hàng trưng bày sản phẩm máy sấy thực phẩm đa năng.Máy sấy đa năng SUNSAY là dòng máy sấy sử dụng công nghệ mới nhất hiện nay, có thể tùy chỉnh chế độ sấy khô – sấy dẻo các sản phẩm trái cây, sấy khô nông sản, thực phẩm, thủy hải sản, dược liệu…\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"AO_-JJ9cp2\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Nguồn Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            contentEn: "{\"time\":1664937785588,\"blocks\":[{\"id\":\"gifxtfLyxG\",\"type\":\"paragraph\",\"data\":{\"text\":\"The Ministry of Science and Technology cooperates with ministries and local agencies to organize the Exhibition and Conference: Science &amp; Technology for Agricultural Development in the South Central Coast - Central Highlands 2018 with the aim of supporting the development agriculture for the South Central Coast region - Central Highlands in the application of science and technology to serve production, build brands, and be competitive enough in the integration period.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"pXtODd1Tvd\",\"type\":\"paragraph\",\"data\":{\"text\":\"The program gathers nearly 400 booths of business units, cooperatives in provinces and cities across the country and foreign businesses developing investment in Vietnam. The main content of the program revolves around the exchange, sharing and exchange of experiences and cooperation between scientists, investors and enterprises on successful achievements of science and technology application in the field of science and technology. Agriculture; linking research institutes, universities with enterprises, cooperatives, and farmer households to help innovate, transfer technology, apply scientific and technological advances to agricultural production and business, and at the same time connect directly with suppliers, transferring prestige and consulting for units to access appropriate preferential policies.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"7oQMS811hZ\",\"type\":\"paragraph\",\"data\":{\"text\":\"Green Technology Vietnam participated in the fair with a booth displaying multi-function food dryer products.\\nSUNSAY multi-function dryer is a line of dryers that uses the latest technology today, can customize the drying mode - flexible drying of fruit products, drying agricultural products, food, seafood, medicinal herbs...&nbsp;\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"P2IBKAm0Om\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Copy Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            avatarUrl: "https://www.anfico.vn/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            avatarPath: "/anfico/storage/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            createdBy: "anfico",
            createdDate: "2022-10-05T02:37:54Z"
        },
        {
            id: 11,
            titleVi: "Kỹ Nghệ Xanh Việt Nam tham gia hội chợ Khoa học – Công nghệ Nam Trung Bộ – Tây Nguyên",
            titleEn: "Vietnam Green Industry participates in Science - Technology Fair South Central - Central Highlands",
            descriptionVi: "Triển lãm và Hội nghị Khoa học & Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 diễn ra từ ngày 28/6 đến hết ngày 01/07/2018 tại Nha Trang, Khánh Hòa.",
            descriptionEn: "Science & Technology Exhibition and Conference for Agricultural Development in the South Central Coast - Central Highlands 2018 took place from June 28 to July 1, 2018 in Nha Trang, Khanh Hoa.",
            contentVi: "{\"time\":1664937785587,\"blocks\":[{\"id\":\"7S--1xGAEf\",\"type\":\"paragraph\",\"data\":{\"text\":\"Bộ Khoa học Công nghệ phối hợp với các bộ, ngành địa phương tổ chức chương trình Triển lãm và Hội nghị: Khoa học &amp; Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 nhằm mục tiêu hỗ trợ phát triển nông nghiệp cho khu vực Duyên hải Nam Trung Bộ – Tây Nguyên trong việc ứng dụng khoa học công nghệ phục vụ sản xuất, xây dựng thương hiệu, đủ sức cạnh tranh trong thời kỳ hội nhập.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"13Yf8hcWBI\",\"type\":\"paragraph\",\"data\":{\"text\":\"Chương trình&nbsp;quy tụ gần 400 gian hàng của các đơn vị doanh nghiệp, hợp tác xã thuộc các tỉnh thành phố trong cả nước cùng các doanh nghiệp nước ngoài đang phát triển đầu tư tại Việt Nam. Nội dung chủ yếu của chương trình xoay quanh việc giao lưu, chia sẻ và trao đổi kinh nghiệm, quan hệ hợp tác giữa các nhà khoa học, các nhà đầu tư cùng doanh nghiệp về những thành tựu ứng dụng KHCN thành công trong lĩnh vực nông nghiệp; liên kết các viện nghiên cứu, các trường đại học với các doanh nghiệp, hợp tác xã, hộ nông dân nhằm giúp đổi mới, chuyển giao công nghệ, ứng dụng tiến bộ KHCN vào sản xuất kinh doanh nông nghiệp, đồng thời kết nối trực tiếp với các nhà cung ứng, chuyển giao uy tín và tư vấn để các đơn vị tiếp cận các chính sách ưu đãi phù hợp.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"qZEg1udWRB\",\"type\":\"paragraph\",\"data\":{\"text\":\"Kỹ Nghệ Xanh Việt Nam tham gia hội chợ với gian hàng trưng bày sản phẩm máy sấy thực phẩm đa năng.Máy sấy đa năng SUNSAY là dòng máy sấy sử dụng công nghệ mới nhất hiện nay, có thể tùy chỉnh chế độ sấy khô – sấy dẻo các sản phẩm trái cây, sấy khô nông sản, thực phẩm, thủy hải sản, dược liệu…\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"AO_-JJ9cp2\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Nguồn Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            contentEn: "{\"time\":1664937785588,\"blocks\":[{\"id\":\"gifxtfLyxG\",\"type\":\"paragraph\",\"data\":{\"text\":\"The Ministry of Science and Technology cooperates with ministries and local agencies to organize the Exhibition and Conference: Science &amp; Technology for Agricultural Development in the South Central Coast - Central Highlands 2018 with the aim of supporting the development agriculture for the South Central Coast region - Central Highlands in the application of science and technology to serve production, build brands, and be competitive enough in the integration period.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"pXtODd1Tvd\",\"type\":\"paragraph\",\"data\":{\"text\":\"The program gathers nearly 400 booths of business units, cooperatives in provinces and cities across the country and foreign businesses developing investment in Vietnam. The main content of the program revolves around the exchange, sharing and exchange of experiences and cooperation between scientists, investors and enterprises on successful achievements of science and technology application in the field of science and technology. Agriculture; linking research institutes, universities with enterprises, cooperatives, and farmer households to help innovate, transfer technology, apply scientific and technological advances to agricultural production and business, and at the same time connect directly with suppliers, transferring prestige and consulting for units to access appropriate preferential policies.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"7oQMS811hZ\",\"type\":\"paragraph\",\"data\":{\"text\":\"Green Technology Vietnam participated in the fair with a booth displaying multi-function food dryer products.\\nSUNSAY multi-function dryer is a line of dryers that uses the latest technology today, can customize the drying mode - flexible drying of fruit products, drying agricultural products, food, seafood, medicinal herbs...&nbsp;\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"P2IBKAm0Om\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Copy Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            avatarUrl: "https://www.anfico.vn/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            avatarPath: "/anfico/storage/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            createdBy: "anfico",
            createdDate: "2022-10-05T02:37:54Z"
        },
        {
            id: 11,
            titleVi: "Kỹ Nghệ Xanh Việt Nam tham gia hội chợ Khoa học – Công nghệ Nam Trung Bộ – Tây Nguyên",
            titleEn: "Vietnam Green Industry participates in Science - Technology Fair South Central - Central Highlands",
            descriptionVi: "Triển lãm và Hội nghị Khoa học & Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 diễn ra từ ngày 28/6 đến hết ngày 01/07/2018 tại Nha Trang, Khánh Hòa.",
            descriptionEn: "Science & Technology Exhibition and Conference for Agricultural Development in the South Central Coast - Central Highlands 2018 took place from June 28 to July 1, 2018 in Nha Trang, Khanh Hoa.",
            contentVi: "{\"time\":1664937785587,\"blocks\":[{\"id\":\"7S--1xGAEf\",\"type\":\"paragraph\",\"data\":{\"text\":\"Bộ Khoa học Công nghệ phối hợp với các bộ, ngành địa phương tổ chức chương trình Triển lãm và Hội nghị: Khoa học &amp; Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 nhằm mục tiêu hỗ trợ phát triển nông nghiệp cho khu vực Duyên hải Nam Trung Bộ – Tây Nguyên trong việc ứng dụng khoa học công nghệ phục vụ sản xuất, xây dựng thương hiệu, đủ sức cạnh tranh trong thời kỳ hội nhập.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"13Yf8hcWBI\",\"type\":\"paragraph\",\"data\":{\"text\":\"Chương trình&nbsp;quy tụ gần 400 gian hàng của các đơn vị doanh nghiệp, hợp tác xã thuộc các tỉnh thành phố trong cả nước cùng các doanh nghiệp nước ngoài đang phát triển đầu tư tại Việt Nam. Nội dung chủ yếu của chương trình xoay quanh việc giao lưu, chia sẻ và trao đổi kinh nghiệm, quan hệ hợp tác giữa các nhà khoa học, các nhà đầu tư cùng doanh nghiệp về những thành tựu ứng dụng KHCN thành công trong lĩnh vực nông nghiệp; liên kết các viện nghiên cứu, các trường đại học với các doanh nghiệp, hợp tác xã, hộ nông dân nhằm giúp đổi mới, chuyển giao công nghệ, ứng dụng tiến bộ KHCN vào sản xuất kinh doanh nông nghiệp, đồng thời kết nối trực tiếp với các nhà cung ứng, chuyển giao uy tín và tư vấn để các đơn vị tiếp cận các chính sách ưu đãi phù hợp.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"qZEg1udWRB\",\"type\":\"paragraph\",\"data\":{\"text\":\"Kỹ Nghệ Xanh Việt Nam tham gia hội chợ với gian hàng trưng bày sản phẩm máy sấy thực phẩm đa năng.Máy sấy đa năng SUNSAY là dòng máy sấy sử dụng công nghệ mới nhất hiện nay, có thể tùy chỉnh chế độ sấy khô – sấy dẻo các sản phẩm trái cây, sấy khô nông sản, thực phẩm, thủy hải sản, dược liệu…\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"AO_-JJ9cp2\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Nguồn Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            contentEn: "{\"time\":1664937785588,\"blocks\":[{\"id\":\"gifxtfLyxG\",\"type\":\"paragraph\",\"data\":{\"text\":\"The Ministry of Science and Technology cooperates with ministries and local agencies to organize the Exhibition and Conference: Science &amp; Technology for Agricultural Development in the South Central Coast - Central Highlands 2018 with the aim of supporting the development agriculture for the South Central Coast region - Central Highlands in the application of science and technology to serve production, build brands, and be competitive enough in the integration period.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"pXtODd1Tvd\",\"type\":\"paragraph\",\"data\":{\"text\":\"The program gathers nearly 400 booths of business units, cooperatives in provinces and cities across the country and foreign businesses developing investment in Vietnam. The main content of the program revolves around the exchange, sharing and exchange of experiences and cooperation between scientists, investors and enterprises on successful achievements of science and technology application in the field of science and technology. Agriculture; linking research institutes, universities with enterprises, cooperatives, and farmer households to help innovate, transfer technology, apply scientific and technological advances to agricultural production and business, and at the same time connect directly with suppliers, transferring prestige and consulting for units to access appropriate preferential policies.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"7oQMS811hZ\",\"type\":\"paragraph\",\"data\":{\"text\":\"Green Technology Vietnam participated in the fair with a booth displaying multi-function food dryer products.\\nSUNSAY multi-function dryer is a line of dryers that uses the latest technology today, can customize the drying mode - flexible drying of fruit products, drying agricultural products, food, seafood, medicinal herbs...&nbsp;\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"P2IBKAm0Om\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Copy Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            avatarUrl: "https://www.anfico.vn/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            avatarPath: "/anfico/storage/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            createdBy: "anfico",
            createdDate: "2022-10-05T02:37:54Z"
        },
        {
            id: 11,
            titleVi: "Kỹ Nghệ Xanh Việt Nam tham gia hội chợ Khoa học – Công nghệ Nam Trung Bộ – Tây Nguyên",
            titleEn: "Vietnam Green Industry participates in Science - Technology Fair South Central - Central Highlands",
            descriptionVi: "Triển lãm và Hội nghị Khoa học & Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 diễn ra từ ngày 28/6 đến hết ngày 01/07/2018 tại Nha Trang, Khánh Hòa.",
            descriptionEn: "Science & Technology Exhibition and Conference for Agricultural Development in the South Central Coast - Central Highlands 2018 took place from June 28 to July 1, 2018 in Nha Trang, Khanh Hoa.",
            contentVi: "{\"time\":1664937785587,\"blocks\":[{\"id\":\"7S--1xGAEf\",\"type\":\"paragraph\",\"data\":{\"text\":\"Bộ Khoa học Công nghệ phối hợp với các bộ, ngành địa phương tổ chức chương trình Triển lãm và Hội nghị: Khoa học &amp; Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 nhằm mục tiêu hỗ trợ phát triển nông nghiệp cho khu vực Duyên hải Nam Trung Bộ – Tây Nguyên trong việc ứng dụng khoa học công nghệ phục vụ sản xuất, xây dựng thương hiệu, đủ sức cạnh tranh trong thời kỳ hội nhập.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"13Yf8hcWBI\",\"type\":\"paragraph\",\"data\":{\"text\":\"Chương trình&nbsp;quy tụ gần 400 gian hàng của các đơn vị doanh nghiệp, hợp tác xã thuộc các tỉnh thành phố trong cả nước cùng các doanh nghiệp nước ngoài đang phát triển đầu tư tại Việt Nam. Nội dung chủ yếu của chương trình xoay quanh việc giao lưu, chia sẻ và trao đổi kinh nghiệm, quan hệ hợp tác giữa các nhà khoa học, các nhà đầu tư cùng doanh nghiệp về những thành tựu ứng dụng KHCN thành công trong lĩnh vực nông nghiệp; liên kết các viện nghiên cứu, các trường đại học với các doanh nghiệp, hợp tác xã, hộ nông dân nhằm giúp đổi mới, chuyển giao công nghệ, ứng dụng tiến bộ KHCN vào sản xuất kinh doanh nông nghiệp, đồng thời kết nối trực tiếp với các nhà cung ứng, chuyển giao uy tín và tư vấn để các đơn vị tiếp cận các chính sách ưu đãi phù hợp.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"qZEg1udWRB\",\"type\":\"paragraph\",\"data\":{\"text\":\"Kỹ Nghệ Xanh Việt Nam tham gia hội chợ với gian hàng trưng bày sản phẩm máy sấy thực phẩm đa năng.Máy sấy đa năng SUNSAY là dòng máy sấy sử dụng công nghệ mới nhất hiện nay, có thể tùy chỉnh chế độ sấy khô – sấy dẻo các sản phẩm trái cây, sấy khô nông sản, thực phẩm, thủy hải sản, dược liệu…\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"AO_-JJ9cp2\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Nguồn Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            contentEn: "{\"time\":1664937785588,\"blocks\":[{\"id\":\"gifxtfLyxG\",\"type\":\"paragraph\",\"data\":{\"text\":\"The Ministry of Science and Technology cooperates with ministries and local agencies to organize the Exhibition and Conference: Science &amp; Technology for Agricultural Development in the South Central Coast - Central Highlands 2018 with the aim of supporting the development agriculture for the South Central Coast region - Central Highlands in the application of science and technology to serve production, build brands, and be competitive enough in the integration period.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"pXtODd1Tvd\",\"type\":\"paragraph\",\"data\":{\"text\":\"The program gathers nearly 400 booths of business units, cooperatives in provinces and cities across the country and foreign businesses developing investment in Vietnam. The main content of the program revolves around the exchange, sharing and exchange of experiences and cooperation between scientists, investors and enterprises on successful achievements of science and technology application in the field of science and technology. Agriculture; linking research institutes, universities with enterprises, cooperatives, and farmer households to help innovate, transfer technology, apply scientific and technological advances to agricultural production and business, and at the same time connect directly with suppliers, transferring prestige and consulting for units to access appropriate preferential policies.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"7oQMS811hZ\",\"type\":\"paragraph\",\"data\":{\"text\":\"Green Technology Vietnam participated in the fair with a booth displaying multi-function food dryer products.\\nSUNSAY multi-function dryer is a line of dryers that uses the latest technology today, can customize the drying mode - flexible drying of fruit products, drying agricultural products, food, seafood, medicinal herbs...&nbsp;\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"P2IBKAm0Om\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Copy Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            avatarUrl: "https://www.anfico.vn/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            avatarPath: "/anfico/storage/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            createdBy: "anfico",
            createdDate: "2022-10-05T02:37:54Z"
        },
    ],
    newsActiveList: [
        {
            id: 11,
            titleVi: "Kỹ Nghệ Xanh Việt Nam tham gia hội chợ Khoa học – Công nghệ Nam Trung Bộ – Tây Nguyên",
            titleEn: "Vietnam Green Industry participates in Science - Technology Fair South Central - Central Highlands",
            descriptionVi: "Triển lãm và Hội nghị Khoa học & Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 diễn ra từ ngày 28/6 đến hết ngày 01/07/2018 tại Nha Trang, Khánh Hòa.",
            descriptionEn: "Science & Technology Exhibition and Conference for Agricultural Development in the South Central Coast - Central Highlands 2018 took place from June 28 to July 1, 2018 in Nha Trang, Khanh Hoa.",
            contentVi: "{\"time\":1664937785587,\"blocks\":[{\"id\":\"7S--1xGAEf\",\"type\":\"paragraph\",\"data\":{\"text\":\"Bộ Khoa học Công nghệ phối hợp với các bộ, ngành địa phương tổ chức chương trình Triển lãm và Hội nghị: Khoa học &amp; Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 nhằm mục tiêu hỗ trợ phát triển nông nghiệp cho khu vực Duyên hải Nam Trung Bộ – Tây Nguyên trong việc ứng dụng khoa học công nghệ phục vụ sản xuất, xây dựng thương hiệu, đủ sức cạnh tranh trong thời kỳ hội nhập.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"13Yf8hcWBI\",\"type\":\"paragraph\",\"data\":{\"text\":\"Chương trình&nbsp;quy tụ gần 400 gian hàng của các đơn vị doanh nghiệp, hợp tác xã thuộc các tỉnh thành phố trong cả nước cùng các doanh nghiệp nước ngoài đang phát triển đầu tư tại Việt Nam. Nội dung chủ yếu của chương trình xoay quanh việc giao lưu, chia sẻ và trao đổi kinh nghiệm, quan hệ hợp tác giữa các nhà khoa học, các nhà đầu tư cùng doanh nghiệp về những thành tựu ứng dụng KHCN thành công trong lĩnh vực nông nghiệp; liên kết các viện nghiên cứu, các trường đại học với các doanh nghiệp, hợp tác xã, hộ nông dân nhằm giúp đổi mới, chuyển giao công nghệ, ứng dụng tiến bộ KHCN vào sản xuất kinh doanh nông nghiệp, đồng thời kết nối trực tiếp với các nhà cung ứng, chuyển giao uy tín và tư vấn để các đơn vị tiếp cận các chính sách ưu đãi phù hợp.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"qZEg1udWRB\",\"type\":\"paragraph\",\"data\":{\"text\":\"Kỹ Nghệ Xanh Việt Nam tham gia hội chợ với gian hàng trưng bày sản phẩm máy sấy thực phẩm đa năng.Máy sấy đa năng SUNSAY là dòng máy sấy sử dụng công nghệ mới nhất hiện nay, có thể tùy chỉnh chế độ sấy khô – sấy dẻo các sản phẩm trái cây, sấy khô nông sản, thực phẩm, thủy hải sản, dược liệu…\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"AO_-JJ9cp2\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Nguồn Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            contentEn: "{\"time\":1664937785588,\"blocks\":[{\"id\":\"gifxtfLyxG\",\"type\":\"paragraph\",\"data\":{\"text\":\"The Ministry of Science and Technology cooperates with ministries and local agencies to organize the Exhibition and Conference: Science &amp; Technology for Agricultural Development in the South Central Coast - Central Highlands 2018 with the aim of supporting the development agriculture for the South Central Coast region - Central Highlands in the application of science and technology to serve production, build brands, and be competitive enough in the integration period.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"pXtODd1Tvd\",\"type\":\"paragraph\",\"data\":{\"text\":\"The program gathers nearly 400 booths of business units, cooperatives in provinces and cities across the country and foreign businesses developing investment in Vietnam. The main content of the program revolves around the exchange, sharing and exchange of experiences and cooperation between scientists, investors and enterprises on successful achievements of science and technology application in the field of science and technology. Agriculture; linking research institutes, universities with enterprises, cooperatives, and farmer households to help innovate, transfer technology, apply scientific and technological advances to agricultural production and business, and at the same time connect directly with suppliers, transferring prestige and consulting for units to access appropriate preferential policies.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"7oQMS811hZ\",\"type\":\"paragraph\",\"data\":{\"text\":\"Green Technology Vietnam participated in the fair with a booth displaying multi-function food dryer products.\\nSUNSAY multi-function dryer is a line of dryers that uses the latest technology today, can customize the drying mode - flexible drying of fruit products, drying agricultural products, food, seafood, medicinal herbs...&nbsp;\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"P2IBKAm0Om\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Copy Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            avatarUrl: "https://www.anfico.vn/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            avatarPath: "/anfico/storage/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            createdBy: "anfico",
            createdDate: "2022-10-05T02:37:54Z"
        },
        {
            id: 11,
            titleVi: "Kỹ Nghệ Xanh Việt Nam tham gia hội chợ Khoa học – Công nghệ Nam Trung Bộ – Tây Nguyên",
            titleEn: "Vietnam Green Industry participates in Science - Technology Fair South Central - Central Highlands",
            descriptionVi: "Triển lãm và Hội nghị Khoa học & Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 diễn ra từ ngày 28/6 đến hết ngày 01/07/2018 tại Nha Trang, Khánh Hòa.",
            descriptionEn: "Science & Technology Exhibition and Conference for Agricultural Development in the South Central Coast - Central Highlands 2018 took place from June 28 to July 1, 2018 in Nha Trang, Khanh Hoa.",
            contentVi: "{\"time\":1664937785587,\"blocks\":[{\"id\":\"7S--1xGAEf\",\"type\":\"paragraph\",\"data\":{\"text\":\"Bộ Khoa học Công nghệ phối hợp với các bộ, ngành địa phương tổ chức chương trình Triển lãm và Hội nghị: Khoa học &amp; Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 nhằm mục tiêu hỗ trợ phát triển nông nghiệp cho khu vực Duyên hải Nam Trung Bộ – Tây Nguyên trong việc ứng dụng khoa học công nghệ phục vụ sản xuất, xây dựng thương hiệu, đủ sức cạnh tranh trong thời kỳ hội nhập.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"13Yf8hcWBI\",\"type\":\"paragraph\",\"data\":{\"text\":\"Chương trình&nbsp;quy tụ gần 400 gian hàng của các đơn vị doanh nghiệp, hợp tác xã thuộc các tỉnh thành phố trong cả nước cùng các doanh nghiệp nước ngoài đang phát triển đầu tư tại Việt Nam. Nội dung chủ yếu của chương trình xoay quanh việc giao lưu, chia sẻ và trao đổi kinh nghiệm, quan hệ hợp tác giữa các nhà khoa học, các nhà đầu tư cùng doanh nghiệp về những thành tựu ứng dụng KHCN thành công trong lĩnh vực nông nghiệp; liên kết các viện nghiên cứu, các trường đại học với các doanh nghiệp, hợp tác xã, hộ nông dân nhằm giúp đổi mới, chuyển giao công nghệ, ứng dụng tiến bộ KHCN vào sản xuất kinh doanh nông nghiệp, đồng thời kết nối trực tiếp với các nhà cung ứng, chuyển giao uy tín và tư vấn để các đơn vị tiếp cận các chính sách ưu đãi phù hợp.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"qZEg1udWRB\",\"type\":\"paragraph\",\"data\":{\"text\":\"Kỹ Nghệ Xanh Việt Nam tham gia hội chợ với gian hàng trưng bày sản phẩm máy sấy thực phẩm đa năng.Máy sấy đa năng SUNSAY là dòng máy sấy sử dụng công nghệ mới nhất hiện nay, có thể tùy chỉnh chế độ sấy khô – sấy dẻo các sản phẩm trái cây, sấy khô nông sản, thực phẩm, thủy hải sản, dược liệu…\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"AO_-JJ9cp2\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Nguồn Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            contentEn: "{\"time\":1664937785588,\"blocks\":[{\"id\":\"gifxtfLyxG\",\"type\":\"paragraph\",\"data\":{\"text\":\"The Ministry of Science and Technology cooperates with ministries and local agencies to organize the Exhibition and Conference: Science &amp; Technology for Agricultural Development in the South Central Coast - Central Highlands 2018 with the aim of supporting the development agriculture for the South Central Coast region - Central Highlands in the application of science and technology to serve production, build brands, and be competitive enough in the integration period.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"pXtODd1Tvd\",\"type\":\"paragraph\",\"data\":{\"text\":\"The program gathers nearly 400 booths of business units, cooperatives in provinces and cities across the country and foreign businesses developing investment in Vietnam. The main content of the program revolves around the exchange, sharing and exchange of experiences and cooperation between scientists, investors and enterprises on successful achievements of science and technology application in the field of science and technology. Agriculture; linking research institutes, universities with enterprises, cooperatives, and farmer households to help innovate, transfer technology, apply scientific and technological advances to agricultural production and business, and at the same time connect directly with suppliers, transferring prestige and consulting for units to access appropriate preferential policies.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"7oQMS811hZ\",\"type\":\"paragraph\",\"data\":{\"text\":\"Green Technology Vietnam participated in the fair with a booth displaying multi-function food dryer products.\\nSUNSAY multi-function dryer is a line of dryers that uses the latest technology today, can customize the drying mode - flexible drying of fruit products, drying agricultural products, food, seafood, medicinal herbs...&nbsp;\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"P2IBKAm0Om\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Copy Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            avatarUrl: "https://www.anfico.vn/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            avatarPath: "/anfico/storage/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            createdBy: "anfico",
            createdDate: "2022-10-05T02:37:54Z"
        },
        {
            id: 11,
            titleVi: "Kỹ Nghệ Xanh Việt Nam tham gia hội chợ Khoa học – Công nghệ Nam Trung Bộ – Tây Nguyên",
            titleEn: "Vietnam Green Industry participates in Science - Technology Fair South Central - Central Highlands",
            descriptionVi: "Triển lãm và Hội nghị Khoa học & Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 diễn ra từ ngày 28/6 đến hết ngày 01/07/2018 tại Nha Trang, Khánh Hòa.",
            descriptionEn: "Science & Technology Exhibition and Conference for Agricultural Development in the South Central Coast - Central Highlands 2018 took place from June 28 to July 1, 2018 in Nha Trang, Khanh Hoa.",
            contentVi: "{\"time\":1664937785587,\"blocks\":[{\"id\":\"7S--1xGAEf\",\"type\":\"paragraph\",\"data\":{\"text\":\"Bộ Khoa học Công nghệ phối hợp với các bộ, ngành địa phương tổ chức chương trình Triển lãm và Hội nghị: Khoa học &amp; Công nghệ phát triển nông nghiệp vùng duyên hải Nam Trung bộ – Tây Nguyên 2018 nhằm mục tiêu hỗ trợ phát triển nông nghiệp cho khu vực Duyên hải Nam Trung Bộ – Tây Nguyên trong việc ứng dụng khoa học công nghệ phục vụ sản xuất, xây dựng thương hiệu, đủ sức cạnh tranh trong thời kỳ hội nhập.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"13Yf8hcWBI\",\"type\":\"paragraph\",\"data\":{\"text\":\"Chương trình&nbsp;quy tụ gần 400 gian hàng của các đơn vị doanh nghiệp, hợp tác xã thuộc các tỉnh thành phố trong cả nước cùng các doanh nghiệp nước ngoài đang phát triển đầu tư tại Việt Nam. Nội dung chủ yếu của chương trình xoay quanh việc giao lưu, chia sẻ và trao đổi kinh nghiệm, quan hệ hợp tác giữa các nhà khoa học, các nhà đầu tư cùng doanh nghiệp về những thành tựu ứng dụng KHCN thành công trong lĩnh vực nông nghiệp; liên kết các viện nghiên cứu, các trường đại học với các doanh nghiệp, hợp tác xã, hộ nông dân nhằm giúp đổi mới, chuyển giao công nghệ, ứng dụng tiến bộ KHCN vào sản xuất kinh doanh nông nghiệp, đồng thời kết nối trực tiếp với các nhà cung ứng, chuyển giao uy tín và tư vấn để các đơn vị tiếp cận các chính sách ưu đãi phù hợp.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"qZEg1udWRB\",\"type\":\"paragraph\",\"data\":{\"text\":\"Kỹ Nghệ Xanh Việt Nam tham gia hội chợ với gian hàng trưng bày sản phẩm máy sấy thực phẩm đa năng.Máy sấy đa năng SUNSAY là dòng máy sấy sử dụng công nghệ mới nhất hiện nay, có thể tùy chỉnh chế độ sấy khô – sấy dẻo các sản phẩm trái cây, sấy khô nông sản, thực phẩm, thủy hải sản, dược liệu…\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"AO_-JJ9cp2\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Nguồn Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            contentEn: "{\"time\":1664937785588,\"blocks\":[{\"id\":\"gifxtfLyxG\",\"type\":\"paragraph\",\"data\":{\"text\":\"The Ministry of Science and Technology cooperates with ministries and local agencies to organize the Exhibition and Conference: Science &amp; Technology for Agricultural Development in the South Central Coast - Central Highlands 2018 with the aim of supporting the development agriculture for the South Central Coast region - Central Highlands in the application of science and technology to serve production, build brands, and be competitive enough in the integration period.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"pXtODd1Tvd\",\"type\":\"paragraph\",\"data\":{\"text\":\"The program gathers nearly 400 booths of business units, cooperatives in provinces and cities across the country and foreign businesses developing investment in Vietnam. The main content of the program revolves around the exchange, sharing and exchange of experiences and cooperation between scientists, investors and enterprises on successful achievements of science and technology application in the field of science and technology. Agriculture; linking research institutes, universities with enterprises, cooperatives, and farmer households to help innovate, transfer technology, apply scientific and technological advances to agricultural production and business, and at the same time connect directly with suppliers, transferring prestige and consulting for units to access appropriate preferential policies.\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"7oQMS811hZ\",\"type\":\"paragraph\",\"data\":{\"text\":\"Green Technology Vietnam participated in the fair with a booth displaying multi-function food dryer products.\\nSUNSAY multi-function dryer is a line of dryers that uses the latest technology today, can customize the drying mode - flexible drying of fruit products, drying agricultural products, food, seafood, medicinal herbs...&nbsp;\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}},{\"id\":\"P2IBKAm0Om\",\"type\":\"paragraph\",\"data\":{\"text\":\"<i>Copy Kynghexanh.com.vn</i>\"},\"tunes\":{\"alignTool\":{\"alignment\":\"left\"}}}],\"version\":\"2.25.0\"}",
            avatarUrl: "https://www.anfico.vn/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            avatarPath: "/anfico/storage/image/1664937474088のetal-near-gray-brick-1474993-698x465.jpg",
            createdBy: "anfico",
            createdDate: "2022-10-05T02:37:54Z"
        },
        
    ],
    total: 5,
    isLoading: false,
    currentPage: 0,
}


export default function Banner() {
//   const dispatch = useAppDispatch();
//   const newsData = useAppSelector((state) => state.newsSlice);
//   const translate = useAppSelector((state) => state.translateSlice);

  useEffect(() => {
    // dispatch(getNewsActive());
  }, []);

  return newsData.newsActiveList.length > 0 ? (
    <div className="px-4 sm:px-0 bg-[#9CB148] pt-[50px] pb-[20px]  2xl:h-auto h-auto md:w-auto  text-white-color  ">
      <div className=" container grid lg:grid-cols-2 lg:gap-[54px] lssm:grid-cols-1">
        <Link to={`${newsData.newsActiveList[0].id}`}>
          <div className=" xl:h-[300px] 2xl:w-[777px] 2xl:h-[400px] w-1920:h-[474px] md:w-full  sc991:w-full max-w-full rounded-[10px] overflow-hidden">
            <img
              src={newsData.newsActiveList[0].avatarUrl}
              alt="news1"
              className="w-full object-cover h-full"
            />
          </div>
          <div>
            {/* <p className="my-[28px]">{getDate(newsData.newsActiveList[0].createdDate+"")} - Anfico</p> */}
            <h3 className="leading-normal 2xl:text-[32px] text-white mt-[12px] 2xl:mt-[28px] font-semibold mb-[12px] w-1920:mb-[30px] line-clamp-2 lssm:text-px16 lssm:text-left sm:text-left  md:text-px28 sc991:text-[32px] ">
              {/* {translate.isEnglish
 
                  ? newsData.newsActiveList[0].titleVi
                : newsData.newsActiveList[0].titleEn
               } */}
               {newsData.newsActiveList[0].titleVi}
            </h3>

            <p className="lssm:text-px14 2xl:text-px16 line-clamp-3 text-white xl:line-clamp-2 w-1920:line-clamp-3 sc991:text-px16 sc991:text-left">
              {/* {translate.isEnglish
                  ? newsData.newsActiveList[0].descriptionVi
                  : newsData.newsActiveList[0].descriptionEn
              } */}
              {newsData.newsActiveList[0].descriptionVi}
            </p>
          </div>
        </Link>

        <div className="mt-[53px] lg:mt-0 text-white-color">
          {newsData.newsActiveList[1] && (
              <NewsItem news={newsData.newsActiveList[1]} type={true} />

          )}
          {newsData.newsActiveList[2] && (
              <NewsItem news={newsData.newsActiveList[2]} type={true} />
          )}
          {newsData.newsActiveList[3] && (
              <NewsItem news={newsData.newsActiveList[3]} type={true} />
          )}
        </div>
      </div>
    </div>
  ) : (
    <div className="h-[30px]"></div>
  );
}
