export const apis = {
    user: "user",
    banner: "banners",
    image: "upload-image",
    video: "upload-video",
    file: "upload-file",
    policy: "policy",
    contact: "contacts",
    infrastructures: "infrastructures",
    thanksCustomer: "reviews",
    category: "categories",
    product: "products",
    vouchers: "vouchers",
    recruit: "recruits",
    comment: "comments",
}