export const apis = {
    user: "user",
    banner: "banners",
    image: "upload-image",
    video: "upload-video",
    file: "upload-file",
    policy: "policy",
    contact: "contacts",
    searchContact: "admin/_search/contacts",
    infrastructures: "infrastructures",
    thanksCustomer: "reviews",
    recruit: "recruits",
    new:'news',
    searchNew: "_search/news",
    books: "books",
    category: "categories",
    product: "products",
    vouchers: "vouchers",
    bills: "bills",
    comment: "comments",
}